/*  Program generated by teval1, a translator and LHS/PRCC evaluator written by Jose L. Segovia,  2002-03, for the Kirschner Lab.  */ 
#include <stdio.h> 
#include <stdlib.h> 
#include <math.h>  
#include <time.h>  
#include <string.h> 
#include "datatype.h"
#define NRANSI 
#include "my_nr.h"
#include "nrutil.h"
double dxsav,*xp,**py;  /* defining declarations */ 
int kmax,kount; 
int nrhs;   /* counts function evaluations */ 
#define NINC 11
#define N 5
#define NFigs 5
	 int myreturnsyscall = 0;

void derivs(double TimeAct, double y[], double dydx[], double C[], double AUX[]) 
{
	nrhs++; 
	AUX[1]=  C[9];  		 /* trucks_in=w1; */
	AUX[2]=  C[9];  		 /* queue_line_a=w1; */
	AUX[3]=  C[9];  		 /* queue_line_b=w1; */
}
void load_constants(double C[]) {  
	 /* Filling initial conditions */ 
	 C[1] =  10 ; 		 /* trucks_init=10 5 25 45 $U ; */
	 C[2] =  50 ; 		 /* percentage_dis=50 10 50 90 $U ; */
	 C[3] =  2 ; 		 /* distance_speed=2 2 4 6 $U ; */
	 C[4] =  10 ; 		 /* flow_left=10 5 15 20 $U ; */
	 C[5] =  10 ; 		 /* flow_right=10 5 15 20 $U ; */
	 C[6] =  20 ; 		 /* flow_up=20 15 25 50 $U ; */
	 C[7] =  20 ; 		 /* flow_down=20 15 25 50 $U ; */
	 C[8] =  0.2 ; 		 /* percentage_minimum_dist=0.2 0.1 0.25 0.5 $U ; */
	 C[9] =  0 ; 		 /* w1=0 ; */
	 } 
/* End of loading constants */ 
void load_auxlevel(double AUX[], double y[], double C[]) {
	 /* Filling leval and aux variables with initial conditions */ 
	 AUX[1] =  0.0; 	 /* trucks_in = */ 
	 AUX[2] =  0.0; 	 /* queue_line_a = */ 
	 AUX[3] =  0.0; 	 /* queue_line_b = */ 
} 


void update_variables_lhs(int c, double C[]) { 
	 /* Updates the following variables at point given by c */ 
	 
	 if (c == 0)   { 
 		 C[1] = 31.8; 
 		 C[2] = 12.4; 
 		 C[3] = 4.28; 
 		 C[4] = 5.45; 
 		 C[5] = 8.75; 
 		 C[6] = 16.75; 
 		 C[7] = 16.05; 
 		 C[8] = 0.408; 
	 } 
	 if (c == 1)   { 
 		 C[1] = 12.6; 
 		 C[2] = 30; 
 		 C[3] = 3.16; 
 		 C[4] = 19.25; 
 		 C[5] = 8.45; 
 		 C[6] = 32.15; 
 		 C[7] = 19.55; 
 		 C[8] = 0.368; 
	 } 
	 if (c == 2)   { 
 		 C[1] = 26.2; 
 		 C[2] = 78; 
 		 C[3] = 4.44; 
 		 C[4] = 13.55; 
 		 C[5] = 5.75; 
 		 C[6] = 44.75; 
 		 C[7] = 39.15; 
 		 C[8] = 0.16; 
	 } 
	 if (c == 3)   { 
 		 C[1] = 32.6; 
 		 C[2] = 14; 
 		 C[3] = 2.84; 
 		 C[4] = 11.45; 
 		 C[5] = 15.65; 
 		 C[6] = 18.15; 
 		 C[7] = 18.15; 
 		 C[8] = 0.448; 
	 } 
	 if (c == 4)   { 
 		 C[1] = 30.2; 
 		 C[2] = 74.8; 
 		 C[3] = 4.6; 
 		 C[4] = 5.75; 
 		 C[5] = 5.15; 
 		 C[6] = 20.25; 
 		 C[7] = 47.55; 
 		 C[8] = 0.328; 
	 } 
	 if (c == 5)   { 
 		 C[1] = 31; 
 		 C[2] = 55.6; 
 		 C[3] = 3.64; 
 		 C[4] = 5.15; 
 		 C[5] = 12.65; 
 		 C[6] = 43.35; 
 		 C[7] = 20.95; 
 		 C[8] = 0.288; 
	 } 
	 if (c == 6)   { 
 		 C[1] = 19.8; 
 		 C[2] = 38; 
 		 C[3] = 5.88; 
 		 C[4] = 18.35; 
 		 C[5] = 18.35; 
 		 C[6] = 31.45; 
 		 C[7] = 23.05; 
 		 C[8] = 0.184; 
	 } 
	 if (c == 7)   { 
 		 C[1] = 13.4; 
 		 C[2] = 66.8; 
 		 C[3] = 5.24; 
 		 C[4] = 6.35; 
 		 C[5] = 6.65; 
 		 C[6] = 22.35; 
 		 C[7] = 20.25; 
 		 C[8] = 0.168; 
	 } 
	 if (c == 8)   { 
 		 C[1] = 43; 
 		 C[2] = 23.6; 
 		 C[3] = 2.76; 
 		 C[4] = 10.85; 
 		 C[5] = 6.05; 
 		 C[6] = 37.05; 
 		 C[7] = 29.35; 
 		 C[8] = 0.216; 
	 } 
	 if (c == 9)   { 
 		 C[1] = 39; 
 		 C[2] = 81.2; 
 		 C[3] = 5.08; 
 		 C[4] = 6.95; 
 		 C[5] = 19.55; 
 		 C[6] = 39.15; 
 		 C[7] = 32.85; 
 		 C[8] = 0.432; 
	 } 
	 if (c == 10)   { 
 		 C[1] = 10.2; 
 		 C[2] = 62; 
 		 C[3] = 3.24; 
 		 C[4] = 13.25; 
 		 C[5] = 11.45; 
 		 C[6] = 25.85; 
 		 C[7] = 15.35; 
 		 C[8] = 0.24; 
	 } 
	 if (c == 11)   { 
 		 C[1] = 44.6; 
 		 C[2] = 41.2; 
 		 C[3] = 3.32; 
 		 C[4] = 9.05; 
 		 C[5] = 15.05; 
 		 C[6] = 15.35; 
 		 C[7] = 37.05; 
 		 C[8] = 0.248; 
	 } 
	 if (c == 12)   { 
 		 C[1] = 41.4; 
 		 C[2] = 31.6; 
 		 C[3] = 2.28; 
 		 C[4] = 8.15; 
 		 C[5] = 6.35; 
 		 C[6] = 45.45; 
 		 C[7] = 30.05; 
 		 C[8] = 0.176; 
	 } 
	 if (c == 13)   { 
 		 C[1] = 15; 
 		 C[2] = 36.4; 
 		 C[3] = 4.68; 
 		 C[4] = 9.35; 
 		 C[5] = 19.85; 
 		 C[6] = 24.45; 
 		 C[7] = 30.75; 
 		 C[8] = 0.232; 
	 } 
	 if (c == 14)   { 
 		 C[1] = 24.6; 
 		 C[2] = 52.4; 
 		 C[3] = 3.72; 
 		 C[4] = 6.05; 
 		 C[5] = 14.75; 
 		 C[6] = 16.05; 
 		 C[7] = 45.45; 
 		 C[8] = 0.472; 
	 } 
	 if (c == 15)   { 
 		 C[1] = 7; 
 		 C[2] = 10.8; 
 		 C[3] = 3; 
 		 C[4] = 15.65; 
 		 C[5] = 17.45; 
 		 C[6] = 19.55; 
 		 C[7] = 25.85; 
 		 C[8] = 0.192; 
	 } 
	 if (c == 16)   { 
 		 C[1] = 23; 
 		 C[2] = 34.8; 
 		 C[3] = 5.32; 
 		 C[4] = 15.35; 
 		 C[5] = 17.15; 
 		 C[6] = 32.85; 
 		 C[7] = 33.55; 
 		 C[8] = 0.144; 
	 } 
	 if (c == 17)   { 
 		 C[1] = 17.4; 
 		 C[2] = 82.8; 
 		 C[3] = 3.88; 
 		 C[4] = 15.95; 
 		 C[5] = 12.05; 
 		 C[6] = 30.75; 
 		 C[7] = 16.75; 
 		 C[8] = 0.296; 
	 } 
	 if (c == 18)   { 
 		 C[1] = 18.2; 
 		 C[2] = 63.6; 
 		 C[3] = 4.76; 
 		 C[4] = 7.85; 
 		 C[5] = 13.55; 
 		 C[6] = 26.55; 
 		 C[7] = 44.05; 
 		 C[8] = 0.336; 
	 } 
	 if (c == 19)   { 
 		 C[1] = 19; 
 		 C[2] = 58.8; 
 		 C[3] = 2.2; 
 		 C[4] = 11.75; 
 		 C[5] = 19.25; 
 		 C[6] = 37.75; 
 		 C[7] = 35.65; 
 		 C[8] = 0.4; 
	 } 
	 if (c == 20)   { 
 		 C[1] = 35; 
 		 C[2] = 65.2; 
 		 C[3] = 3.8; 
 		 C[4] = 11.15; 
 		 C[5] = 6.95; 
 		 C[6] = 33.55; 
 		 C[7] = 24.45; 
 		 C[8] = 0.488; 
	 } 
	 if (c == 21)   { 
 		 C[1] = 5.4; 
 		 C[2] = 70; 
 		 C[3] = 2.12; 
 		 C[4] = 18.95; 
 		 C[5] = 16.55; 
 		 C[6] = 49.65; 
 		 C[7] = 37.75; 
 		 C[8] = 0.376; 
	 } 
	 if (c == 22)   { 
 		 C[1] = 34.2; 
 		 C[2] = 76.4; 
 		 C[3] = 3.96; 
 		 C[4] = 9.65; 
 		 C[5] = 10.55; 
 		 C[6] = 23.75; 
 		 C[7] = 46.85; 
 		 C[8] = 0.136; 
	 } 
	 if (c == 23)   { 
 		 C[1] = 33.4; 
 		 C[2] = 15.6; 
 		 C[3] = 4.84; 
 		 C[4] = 16.85; 
 		 C[5] = 14.45; 
 		 C[6] = 36.35; 
 		 C[7] = 22.35; 
 		 C[8] = 0.392; 
	 } 
	 if (c == 24)   { 
 		 C[1] = 8.6; 
 		 C[2] = 18.8; 
 		 C[3] = 5.56; 
 		 C[4] = 13.85; 
 		 C[5] = 18.65; 
 		 C[6] = 18.85; 
 		 C[7] = 41.25; 
 		 C[8] = 0.384; 
	 } 
	 if (c == 25)   { 
 		 C[1] = 35.8; 
 		 C[2] = 79.6; 
 		 C[3] = 2.92; 
 		 C[4] = 8.75; 
 		 C[5] = 16.85; 
 		 C[6] = 41.95; 
 		 C[7] = 34.95; 
 		 C[8] = 0.272; 
	 } 
	 if (c == 26)   { 
 		 C[1] = 23.8; 
 		 C[2] = 54; 
 		 C[3] = 2.68; 
 		 C[4] = 10.25; 
 		 C[5] = 18.95; 
 		 C[6] = 35.65; 
 		 C[7] = 31.45; 
 		 C[8] = 0.36; 
	 } 
	 if (c == 27)   { 
 		 C[1] = 22.2; 
 		 C[2] = 84.4; 
 		 C[3] = 4.36; 
 		 C[4] = 19.85; 
 		 C[5] = 5.45; 
 		 C[6] = 41.25; 
 		 C[7] = 43.35; 
 		 C[8] = 0.464; 
	 } 
	 if (c == 28)   { 
 		 C[1] = 21.4; 
 		 C[2] = 86; 
 		 C[3] = 2.36; 
 		 C[4] = 16.25; 
 		 C[5] = 7.25; 
 		 C[6] = 48.25; 
 		 C[7] = 21.65; 
 		 C[8] = 0.456; 
	 } 
	 if (c == 29)   { 
 		 C[1] = 9.4; 
 		 C[2] = 50.8; 
 		 C[3] = 3.08; 
 		 C[4] = 14.15; 
 		 C[5] = 9.35; 
 		 C[6] = 28.65; 
 		 C[7] = 17.45; 
 		 C[8] = 0.352; 
	 } 
	 if (c == 30)   { 
 		 C[1] = 20.6; 
 		 C[2] = 49.2; 
 		 C[3] = 4.52; 
 		 C[4] = 8.45; 
 		 C[5] = 11.15; 
 		 C[6] = 29.35; 
 		 C[7] = 34.25; 
 		 C[8] = 0.48; 
	 } 
	 if (c == 31)   { 
 		 C[1] = 27.8; 
 		 C[2] = 22; 
 		 C[3] = 4.2; 
 		 C[4] = 18.05; 
 		 C[5] = 15.35; 
 		 C[6] = 44.05; 
 		 C[7] = 27.25; 
 		 C[8] = 0.12; 
	 } 
	 if (c == 32)   { 
 		 C[1] = 25.4; 
 		 C[2] = 87.6; 
 		 C[3] = 5.64; 
 		 C[4] = 15.05; 
 		 C[5] = 13.85; 
 		 C[6] = 21.65; 
 		 C[7] = 25.15; 
 		 C[8] = 0.112; 
	 } 
	 if (c == 33)   { 
 		 C[1] = 39.8; 
 		 C[2] = 33.2; 
 		 C[3] = 5.72; 
 		 C[4] = 12.05; 
 		 C[5] = 13.25; 
 		 C[6] = 23.05; 
 		 C[7] = 23.75; 
 		 C[8] = 0.496; 
	 } 
	 if (c == 34)   { 
 		 C[1] = 42.2; 
 		 C[2] = 39.6; 
 		 C[3] = 3.56; 
 		 C[4] = 7.55; 
 		 C[5] = 17.75; 
 		 C[6] = 38.45; 
 		 C[7] = 42.65; 
 		 C[8] = 0.416; 
	 } 
	 if (c == 35)   { 
 		 C[1] = 11.8; 
 		 C[2] = 42.8; 
 		 C[3] = 5; 
 		 C[4] = 19.55; 
 		 C[5] = 7.85; 
 		 C[6] = 25.15; 
 		 C[7] = 18.85; 
 		 C[8] = 0.208; 
	 } 
	 if (c == 36)   { 
 		 C[1] = 28.6; 
 		 C[2] = 26.8; 
 		 C[3] = 2.6; 
 		 C[4] = 12.95; 
 		 C[5] = 9.65; 
 		 C[6] = 42.65; 
 		 C[7] = 27.95; 
 		 C[8] = 0.152; 
	 } 
	 if (c == 37)   { 
 		 C[1] = 37.4; 
 		 C[2] = 68.4; 
 		 C[3] = 2.04; 
 		 C[4] = 17.45; 
 		 C[5] = 10.85; 
 		 C[6] = 46.15; 
 		 C[7] = 39.85; 
 		 C[8] = 0.128; 
	 } 
	 if (c == 38)   { 
 		 C[1] = 11; 
 		 C[2] = 20.4; 
 		 C[3] = 4.92; 
 		 C[4] = 16.55; 
 		 C[5] = 12.95; 
 		 C[6] = 34.95; 
 		 C[7] = 41.95; 
 		 C[8] = 0.32; 
	 } 
	 if (c == 39)   { 
 		 C[1] = 6.2; 
 		 C[2] = 25.2; 
 		 C[3] = 4.12; 
 		 C[4] = 18.65; 
 		 C[5] = 7.55; 
 		 C[6] = 40.55; 
 		 C[7] = 28.65; 
 		 C[8] = 0.2; 
	 } 
	 if (c == 40)   { 
 		 C[1] = 36.6; 
 		 C[2] = 17.2; 
 		 C[3] = 2.52; 
 		 C[4] = 12.65; 
 		 C[5] = 16.25; 
 		 C[6] = 39.85; 
 		 C[7] = 26.55; 
 		 C[8] = 0.344; 
	 } 
	 if (c == 41)   { 
 		 C[1] = 38.2; 
 		 C[2] = 89.2; 
 		 C[3] = 5.16; 
 		 C[4] = 10.55; 
 		 C[5] = 14.15; 
 		 C[6] = 34.25; 
 		 C[7] = 40.55; 
 		 C[8] = 0.44; 
	 } 
	 if (c == 42)   { 
 		 C[1] = 29.4; 
 		 C[2] = 47.6; 
 		 C[3] = 5.4; 
 		 C[4] = 7.25; 
 		 C[5] = 11.75; 
 		 C[6] = 46.85; 
 		 C[7] = 46.15; 
 		 C[8] = 0.104; 
	 } 
	 if (c == 43)   { 
 		 C[1] = 40.6; 
 		 C[2] = 71.6; 
 		 C[3] = 4.04; 
 		 C[4] = 14.75; 
 		 C[5] = 8.15; 
 		 C[6] = 17.45; 
 		 C[7] = 49.65; 
 		 C[8] = 0.224; 
	 } 
	 if (c == 44)   { 
 		 C[1] = 7.8; 
 		 C[2] = 46; 
 		 C[3] = 3.4; 
 		 C[4] = 17.75; 
 		 C[5] = 9.05; 
 		 C[6] = 20.95; 
 		 C[7] = 48.95; 
 		 C[8] = 0.304; 
	 } 
	 if (c == 45)   { 
 		 C[1] = 43.8; 
 		 C[2] = 73.2; 
 		 C[3] = 5.96; 
 		 C[4] = 14.45; 
 		 C[5] = 9.95; 
 		 C[6] = 30.05; 
 		 C[7] = 38.45; 
 		 C[8] = 0.28; 
	 } 
	 if (c == 46)   { 
 		 C[1] = 16.6; 
 		 C[2] = 44.4; 
 		 C[3] = 2.44; 
 		 C[4] = 17.15; 
 		 C[5] = 15.95; 
 		 C[6] = 48.95; 
 		 C[7] = 44.75; 
 		 C[8] = 0.264; 
	 } 
	 if (c == 47)   { 
 		 C[1] = 15.8; 
 		 C[2] = 28.4; 
 		 C[3] = 3.48; 
 		 C[4] = 6.65; 
 		 C[5] = 10.25; 
 		 C[6] = 47.55; 
 		 C[7] = 36.35; 
 		 C[8] = 0.256; 
	 } 
	 if (c == 48)   { 
 		 C[1] = 27; 
 		 C[2] = 60.4; 
 		 C[3] = 5.8; 
 		 C[4] = 12.35; 
 		 C[5] = 18.05; 
 		 C[6] = 27.25; 
 		 C[7] = 48.25; 
 		 C[8] = 0.424; 
	 } 
	 if (c == 49)   { 
 		 C[1] = 14.2; 
 		 C[2] = 57.2; 
 		 C[3] = 5.48; 
 		 C[4] = 9.95; 
 		 C[5] = 12.35; 
 		 C[6] = 27.95; 
 		 C[7] = 32.15; 
 		 C[8] = 0.312; 
	 } 
 } /*  End of update_variables_lhs  */ 


static int nfigsloaded; 
int load_data_figures(double FIGS[][MAX_FIGS], eqfig figdata[], int nfigs, int jj, double y[], double C[], double AUX[], double x, FILE * myfile) { 
	 int j = nfigsloaded; 
	 int i; int errorover=0; 
		  FIGS[0][j] = x; 
		  if (! finite(AUX[1])) { printf("Overflow error on variable trucks_in \n"); errorover++; } 
		  FIGS[1][j] = AUX[1];
		  if (figdata[1].max < FIGS[1][j]) { figdata[1].max =  FIGS[1][j]; } 
		  if (figdata[1].min > FIGS[1][j]) { figdata[1].min =  FIGS[1][j]; } 
		  if (! finite(AUX[2])) { printf("Overflow error on variable queue_line_a \n"); errorover++; } 
		  FIGS[2][j] = AUX[2];
		  if (figdata[2].max < FIGS[2][j]) { figdata[2].max =  FIGS[2][j]; } 
		  if (figdata[2].min > FIGS[2][j]) { figdata[2].min =  FIGS[2][j]; } 
		  if (! finite(AUX[3])) { printf("Overflow error on variable queue_line_b \n"); errorover++; } 
		  FIGS[3][j] = AUX[3];
		  if (figdata[3].max < FIGS[3][j]) { figdata[3].max =  FIGS[3][j]; } 
		  if (figdata[3].min > FIGS[3][j]) { figdata[3].min =  FIGS[3][j]; } 
	 nfigsloaded ++;
	 if (nfigsloaded >= MAX_FIGS ) { int xx, yy; 
		 for (xx=0;xx<MAX_FIGS;xx++) { 
		 fprintf(myfile,"%f\t",FIGS[0][xx]); 
		  for (yy=1;yy<=3;yy++) 
			  fprintf(myfile, "%.6e\t",FIGS[yy][xx]); 
		 fprintf(myfile,"\n"); 
} nfigsloaded =0; } 
 return errorover; 
} 


int main (void) 
{ 
	 time_t init_time=time(NULL), end_time; double mydifftime;
	 int i,j, resode=0;  int myc=0; 
	 double h, x=1.0, *y, *dydx, *yout, *C, *AUX; 
	 FILE *stream; 
	 char filename[5]; 
	 int nfigs = 3;
	 eqfig figdata[5];
	 double FIGS[5][MAX_FIGS]; 
	 int maxloop =0, nloop =0; int figres=0; 
	 y    =  dvector(1,N);  
	 dydx =  dvector(1,N); 
	 yout =  dvector(1,N);  
	 C   =   dvector(1,NINC); 
	 AUX =   dvector(1,N); 
	 nfigsloaded = 0; 
	 for(i=1;i<=nfigs;i++) { figdata[i].max = -HUGE_VAL; figdata[i].min=HUGE_VAL; }; 
	  strcpy(figdata[1].name,"trucks_in");
	  strcpy(figdata[2].name,"queue_line_a");
	  strcpy(figdata[3].name,"queue_line_b");
	 while (myc < 50) { 
	 load_constants(C); 
	 update_variables_lhs(myc, C); 
	 load_auxlevel(AUX,y,C); 
	 nfigsloaded = 0; 
	 /* ---rk4--- */ 
	 h = (double)0.1;
	 x = (double)0; 
	 maxloop = (int) (360/h)+1;
	 nloop = 0; 
	 j=0; 
	 printf("Solving run %d \n", myc+1);
	 sprintf(filename, "%04u", myc+1); 
	 stream = fopen(filename,"w"  ); 
	 while(nloop <= maxloop) {
		 if (nloop % (int)ceil(1/h) == 0) {
		 resode=load_data_figures(FIGS, figdata, nfigs, j, y, C, AUX, x,  stream);
		 if (resode > 0) break; 
			 j++; }  
		 derivs(x,y,dydx,C, AUX); 
		 rk4(y,dydx,N,x,h,yout,derivs, C, AUX); 
		 for(i=0; i<N; i++) 
		 y[i] = yout[i]; 
		 nloop++; 
		 x = x + h;
	 }  
	for(i=0; i<nfigsloaded; i++) { 
		 fprintf(stream,"%f\t",FIGS[0][i]);
		 for(j=1; j<=nfigs; j++) fprintf(stream,"%.5e\t",FIGS[j][i]); 
		 fprintf(stream,"\n"); }; 
		 fclose(stream); 
	 if (resode > 0) { printf( "Error solving run %d \n", myc+1); break;	} 
	 myc++; } 
	 WritePlotScript(1, nfigs, 432, figdata, 0, myc-1);
	 myreturnsyscall = system("rm output1.pdf; gnuplot plot.scr &"); 
	 free_dvector(yout,1,N); 
	 free_dvector(dydx,1,N); 
	 free_dvector(y,1,N); 
	 free_dvector(C,1,NINC); 
	 free_dvector(AUX,1,N); 
	 end_time = time(NULL); 
	 mydifftime = difftime(end_time, init_time); 
	 printf("##  %f seconds \n",mydifftime); 
	 return 0; 
} 
